.\"@ s-cdda: access digital audio CDs (TOC, MCN, ISRC, CD-TEXT, audio tracks).
.\"
.\" Copyright (c) 2020 - 2021 Steffen Nurpmeso <steffen@sdaoden.eu>.
.\" SPDX-License-Identifier: ISC
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.
.Dd November 06, 2020
.Dt S-CDDA 1
.Os
.Mx -enable
.
.
.Sh NAME
.Nm s-cdda
.Nd access digital audio CDs (TOC, MCN, ISRC, CD-TEXT, audio tracks)
.
.
.Sh SYNOPSIS
.
.Nm
.Fl h
.Nm
.Fl L
.Pp
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Pf : Fl l Ar LANGUAGE :
.Fl a
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Fl i
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Fl m
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Op Fl t
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Pf : Fl l Ar LANGUAGE :
.Fl x
.Pp
.Nm
.Op Fl nv
.Op Fl d Ar DEVICE
.Fl r Ar NUMBER
.
.
.Mx -toc -tree html pdf ps xhtml
.
.
.Sh DESCRIPTION
.
.Nm
is a simple tool to query information, like table-of-contents, from
audio CD-ROMs.
It can also be used to read audio tracks, and store them as WAVE audio
files.
It only works with SCSI MMC-3 aware cdrom/drivers.
.
.
.Ss "Options"
.
.Bl -tag -width ".It Fl BaNg"
.Mx
.It Fl a
Perform all possible queries.
.
.Mx
.It Fl d Ar DEVICE
Specify the CD-ROM
.Ar DEVICE .
If not given the environment variable
.Ev CDROM
is inspected, a system-dependent value (like
.Pa /dev/cdrom )
is used as a fallback.
.
.Mx
.It Fl h
Show a brief usage summary, then exit.
.
.Mx
.It Fl i
Query the International Standard Recording Code (ISRC) entries,
if available on the CD-ROM and supported by the device.
Quality of service: devices are known which do not find ISRC
subchannel data: repeating the query may succeed.
Is missing on many CD-ROMs.
.
.Mx
.It Fl L
Show list of selectable CD-TEXT languages, then exit.
.
.Mx
.It Fl l Ar LANGUAGE
Add a language, case-insensitively, to the CD-TEXT filter.
If used multiple times, earlier ones take precedence, the best
fitting CD-TEXT entry will be used.
.
.Mx
.It Fl m
Query the Media Catalog Number,
if available on the CD-ROM, and supported by the device.
Quality of service: devices are known which do not find the MCN
subchannel data: repeating the query may succeed.
Is missing on many CD-ROMs.
.
.Mx
.It Fl n
Do not perform sanity checks on data.
May
.Dq pamper
over invalid data!
.
.Mx
.It Fl r Ar NUMBER
Read the audio track
.Ar NUMBER ,
and write it in WAVE format to the standard output.
It will refuse to write if standard output is a terminal.
.
.Mx
.It Fl t
Query the table of contents.
Outputs an audio-only, if available, and a complete table of contents in
a format suitable as input to the
.Xr sh 1 .
.
.Mx
.It Fl v
Be more verbose, dump packets as they are encountered.
.
.Mx
.It Fl x
Collect CD-TEXT information of the desired
.Fl l Ns
anguage, if available on the CD-ROM, and supported by the device.
Is missing on many CD-ROMs.
.El
.
.Sh EXAMPLES
.
.Bd -literal -offset indent
# Dump table of contents
$ s-cdda
# Ditto, show packet data
$ s-cdda -v

# Read track number 2 to track-2.wav
$ s-cdda --read 2 > track-2.wav
.Ed
.
.
.Sh AUTHORS
.
.An Steffen Nurpmeso Aq steffen@sdaoden.eu
.\" s-ts-mode
