#!/bin/sh -
#@ Like shar(1), but with an uuencode(1)/uudecode(1) binary safe layer added.
#@ Member compression via optional --(compress|gzip|bzip2|xz) argument.
#@ Web: http://sdaoden.users.sourceforge.net/code.html;
#@      https://sourceforge.net/projects/s-toolbox
#@ Git: git.code.sf.net/p/s-toolbox/code
#
# Copyright (c) 2012 Steffen Daode Nurpmeso <sdaoden@users.sf.net>.
# All rights reserved.
#
#	$NetBSD: shar.sh,v 1.2 1994/12/21 08:42:04 jtc Exp $
#
# Copyright (c) 1990, 1993
#	The Regents of the University of California.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the University of
#	California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#	@(#)shar.sh	8.1 (Berkeley) 6/6/93
#

if [ $# -eq 0 ]; then
	echo 'usage: uushar [--(compress|gzip|bzip2|xz)] file ...'
	exit 1
fi

x_compress='compress -c -f'
ux_compress='uncompress -c'
x_gzip='gzip -c -f'
ux_gzip='gunzip -c -f'
x_bzip2='bzip2 --compress --stdout'
ux_bzip2='bzip2 --decompress --stdout'
x_xz='xz --compress --stdout'
ux_xz='xz --decompress --stdout'

case $1 in
--*)
	eval cfun='$x_'${1#--}
	eval xfun='$ux_'${1#--}
	if [ -z "$cfun" ]; then
		echo >&2 "Unsupported compression method: $1"
		exit 1
	fi
	shift
	;;
*)
	cfun= xfun= 
	;;
esac

cat << \!
# This is a shell archive.  Save it in a file, remove anything before
# this line, and then unpack it by entering "sh file".  Note, it may
# create directories; files and directories will be owned by you and
# have default permissions.
#
# Archives produced using this implementation of shar may be easily
# examined with the command:
#	$ egrep -v '^[X#]' shell-archive
#
# This archive contains:
!

for i
do
	echo "#	$i"
done
echo '#'

for i
do
	if [ -d $i ]; then
		echo "echo c - $i"
		echo "mkdir -p $i > /dev/null 2>&1"
	elif [ -z "$cfun" ]; then
		echo "echo x - $i"
		echo "sed 's/^X//' << \! | uudecode > $i"
		< $i uuencode -m /dev/stdout | sed 's/^/X/'
		echo '!'
	else
		echo "echo xx - $i"
		echo "sed 's/^X//' << \! | uudecode | $xfun > $i"
		< $i $cfun | uuencode -m /dev/stdout | sed 's/^/X/'
		echo '!'
	fi
done
echo exit
echo

exit
